### PR TITLE
Issue 303 - Use number instead of string for COUNT property in RRULE

### LINKED ISSUE #303: jCal use string for count rrule property instead of number
The [jCal rfc](https://tools.ietf.org/html/rfc7265) specify that COUNT property should be a number in not a string.
But Sabre send this property as a String and fail when parsing jCal with COUNT as a number.

### PR DESCRIPTION
**Pull request by strokyl**
Fixes #303

### CODE REVIEW

File: lib/Property/ICalendar/Recur.php [hunk 1]
```diff
@@ -54,7 +54,7 @@ function setValue($value) {
                     if (strcmp($k, 'until') === 0) {
                         $v = strtr($v, [':' => '', '-' => '']);
                     }
-                } else {
+                } else if (!is_int($v)) {
```
Comment (staabm) [inline lib/Property/ICalendar/Recur.php]: I guess the logic expects a `is_string`?

Comment (strokyl) [inline lib/Property/ICalendar/Recur.php]: Hum if I am not wrong no it's is_int($v), is_string case is handle before, this else if(!is_int($v)) will fail if $v is a int (and not an array) for the int case, there nothing to do just store the value which is done outside the if else if.

Comment (staabm) [inline lib/Property/ICalendar/Recur.php]: you are right, `is_string` is wrong...  `is_array` it is ;-)

File: lib/Property/ICalendar/Recur.php [hunk 2]
```diff
@@ -54,7 +54,7 @@ function setValue($value) {
                     if (strcmp($k, 'until') === 0) {
                         $v = strtr($v, [':' => '', '-' => '']);
                     }
-                } else {
+                } elseif (!is_int($v)) {
```
Comment (evert) [inline lib/Property/ICalendar/Recur.php]: To add to that previous conversation, it might simply be a bit better to use `is_array` and not `is_int`. I think it makes this a bit clearer. Other than that, patch looks good!

Comment (strokyl) [inline lib/Property/ICalendar/Recur.php]: Yes it's better like that, I have fixed it. 
Thank you.
